.PHONY: clean all

# C preprocessor flags
CPPFLAGS ?= -MMD
# C++ compiler flags
CXXFLAGS ?= -Wall -Wextra -Werror -pedantic -O3 -flto --std=c++20

BINS = read-write mmap-mmap mmap-write read-mmap

all: $(BINS)

read-write: read-write.o posix.o
	$(CXX) -o $@ $(CXXFLAGS) $^ $(LDFLAGS)

mmap-mmap: mmap-mmap.o posix.o
	$(CXX) -o $@ $(CXXFLAGS) $^ $(LDFLAGS)

mmap-write: mmap-write.o posix.o
	$(CXX) -o $@ $(CXXFLAGS) $^ $(LDFLAGS)

read-mmap: read-mmap.o posix.o
	$(CXX) -o $@ $(CXXFLAGS) $^ $(LDFLAGS)

clean:
	find . -maxdepth 1 -type f \( -name '*.o' -o -name '*.d' \) -print0 | xargs -0 rm	
	rm -f $(BINS)

# Include the make targets that were generated by the implicit %.o rule, which
# will invoke the C++ compiler and pass it the CPPFLAGS preprocessor flags,
# which contain the "-MMD" argument, which produces a *.d file that relates
# source files to header files included by them.
-include *.d
